### ISSUE TITLE
CinematicStudio插件无法正常使用

### ISSUE THREAD

**Issue by 5ur3z** [MohistMC/Banner#100]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

banner-1.20.1-304.jar

### Java 版本 | 操作系统

系统：Windows 11  Java：zulu18.32.13-ca-jdk18.0.2.1-win_x64

### 相关 Mod/插件 的名称及版本

```raw
CinematicStudio_1.4.4.jar
LoneLibs.jar
ProtocolLib.jar
```

### 错误描述

仅安装了cinematicstudio及其前置
该插件可以做到平滑运镜动画

### 复现步骤

安装CinematicStudio
Lonelibs
ProtocolLib
进入游戏，输入/cinematic edit打开编辑界面
点击new scene输入任意名称后，在弹出的GUI Camera栏中添加一个镜头
输入/cinematic input move 20 smooth添加完毕后，点击Play scene会产生报错1，且客户端HUD消失
再次进入服务器后，输入/cin edit <名称>打开编辑界面，点击Preview Cameras会产生报错2

### 报错信息

----
报错1
----
[18:42:46] [Server thread/WARN]: [CinematicStudio] Task #13 for CinematicStudio v1.4.4 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/network/protocol/game/ClientboundGameEventPacket$a
        at dev.lone.cinematicstudio.nms.aC.impl.v1_20_R1.a(SourceFile:40) ~[?:?]
        at dev.lone.cinematicstudio.nms.aC.aH.j(SourceFile:45) ~[?:?]
        at dev.lone.cinematicstudio.cutscene.CutsceneInstance.startCutscene(SourceFile:233) ~[?:?]
        at dev.lone.cinematicstudio.cutscene.CutsceneManager.playCutscene(SourceFile:30) ~[?:?]
        at dev.lone.cinematicstudio.uibuilder.CutsceneEditor.lambda$getMenu$19(SourceFile:957) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[banner-1.20.1-304.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:421) ~[banner-1.20.1-304.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zdh000$banner$processStart(MinecraftServer.java:2524) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java) ~[server-intermediary.jar:?]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:2133) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.network.protocol.game.ClientboundGameEventPacket$a
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:168) ~[banner-1.20.1-304.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:157) ~[banner-1.20.1-304.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:109) ~[banner-1.20.1-304.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 14 more
[18:42:48] [Server thread/WARN]: [CinematicStudio] Task #40 for CinematicStudio v1.4.4 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/network/protocol/game/ClientboundGameEventPacket$a
        at dev.lone.cinematicstudio.nms.aC.impl.v1_20_R1.a(SourceFile:40) ~[?:?]
        at dev.lone.cinematicstudio.nms.aC.aH.a(SourceFile:57) ~[?:?]
        at dev.lone.cinematicstudio.cutscene.CutsceneInstance.stopCutscene(SourceFile:252) ~[?:?]
        at dev.lone.cinematicstudio.cutscene.CutsceneInstance.lambda$runNode$2(SourceFile:321) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[banner-1.20.1-304.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:421) ~[banner-1.20.1-304.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zdh000$banner$processStart(MinecraftServer.java:2524) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java) ~[server-intermediary.jar:?]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:2133) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.network.protocol.game.ClientboundGameEventPacket$a
        ... 13 more

----
报错2
----

[18:39:43] [Server thread/ERROR]: Could not pass event InventoryClickEvent to CinematicStudio v1.4.4
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[banner-1.20.1-304.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:75) ~[banner-1.20.1-304.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:604) ~[banner-1.20.1-304.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:591) ~[banner-1.20.1-304.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3482) ~[server-intermediary.jar:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[server-intermediary.jar:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[server-intermediary.jar:?]
        at net.minecraft.network.protocol.PacketUtils.md4e3221$banner$lambda$ensureRunningOnSameThread$0$0(PacketUtils.java:529) ~[server-intermediary.jar:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:156) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:782) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:164) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:130) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:764) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:139) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:743) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:2137) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Unable to create packet instance for class class net.minecraft.network.protocol.game.ClientboundCustomPayloadPacket
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at com.comphenix.protocol.injector.StructureCache.lambda$newPacket$2(StructureCache.java:99) ~[?:?]
        at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:103) ~[?:?]
        at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:113) ~[?:?]
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:117) ~[?:?]
        at dev.lone.cinematicstudio.main.a.a(SourceFile:63) ~[?:?]
        at dev.lone.cinematicstudio.uibuilder.CutsceneEditor.lambda$getMenu$24(SourceFile:977) ~[?:?]
        at dev.lone.cinematicstudio.ui.MasterUI.onInventoryClick(SourceFile:170) ~[?:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:311) ~[banner-1.20.1-304.jar:?]
        ... 20 more

**Comment by 5ur3z** [comment]
[plugins.zip](https://github.com/MohistMC/Banner/files/12214169/plugins.zip)

**Comment by 5ur3z** [comment]
报错2还是没修复(
