### ISSUE TITLE
itemadder插件无法正常使用

### ISSUE THREAD

**Issue by 5ur3z** [MohistMC/Banner#102]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

banner-1.20.1-304.jar

### Java 版本 | 操作系统

系统：Windows 11  Java：zulu18.32.13-ca-jdk18.0.2.1-win_x64

### 相关 Mod/插件 的名称及版本

```raw
ItemsAdder_3.5.0.jar
LoneLibs.jar
ProtocolLib.jar
```

### 错误描述

加入itemadders插件后服务器可以正常启动，但是输入/ia打开事例物品时，即使加载了材质包，也只会显示为原版方块/物品
且点击任意物品获取后后台会产生报错1，同#100 issue

### 复现步骤

安装ia及其前置
进入游戏输入/ia打开事例物品时，即使加载了材质包，也只会显示为原版方块/物品
且点击任意物品获取后后台会产生报错1，同#100 issue

### 报错信息

----
报错1
----
[19:14:37] [Server thread/ERROR]: Could not pass event InventoryClickEvent to LoneLibs v1.0.25
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[banner-1.20.1-304.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:75) ~[banner-1.20.1-304.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:604) ~[banner-1.20.1-304.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:591) ~[banner-1.20.1-304.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3482) ~[server-intermediary.jar:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[server-intermediary.jar:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[server-intermediary.jar:?]
        at net.minecraft.network.protocol.PacketUtils.md92fe37$banner$lambda$ensureRunningOnSameThread$0$0(PacketUtils.java:529) ~[server-intermediary.jar:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:156) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:782) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:164) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:130) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:764) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:139) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:743) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:2137) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.get(int)" because "this.h" is null
        at ia.m.hZ.a(SourceFile:109) ~[?:?]
        at ia.m.hY.a(SourceFile:208) ~[?:?]
        at fr.mrmicky.fastinv.FastInv.handleClick(FastInv.java:316) ~[?:?]
        at fr.mrmicky.fastinv.FastInvManager$1.onInventoryClick(FastInvManager.java:50) ~[?:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:311) ~[banner-1.20.1-304.jar:?]
        ... 20 more

----
完整log
----
[latest.log](https://github.com/MohistMC/Banner/files/12214423/latest.log)

**Comment by 5ur3z** [comment]
[plugins.zip](https://github.com/MohistMC/Banner/files/12214475/plugins.zip)
[resourcepacks.zip](https://github.com/MohistMC/Banner/files/12214478/resourcepacks.zip)
