### ISSUE TITLE
Porting Lib和Banner可否实现兼容？

### ISSUE THREAD

**Issue by onecvly** [MohistMC/Banner#127]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [x] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

368

### Java 版本 | 操作系统

系统：Windows 10 家庭中文版|22H2；JAVA版本：Azul Zulu-java-17.0.7

### 相关 Mod/插件 的名称及版本

```raw
porting_lib-2.1.1107+1.20-entity-refactor(Create for Fabric的前置)
```

### 错误描述

看起来像是Mixin注入的错误
这个问题在另外一个混合软件也存在。即在Cardboard下
Porting Lib mod是为方便Forge开发者移植到Fabric端口的mod
包括Create，Hephaestus，The Twilight Forest（目前这些mod在1.20.1版本处于开发状态）
那么Porting Lib和Banner有没有兼容的可能性？

### 复现步骤

将Porting Lib与Banner一同安装，然后启动
结果：崩溃

### 报错信息

[00:53:24] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.22
[00:53:24] [main/INFO]: Loading 103 mods:
	- banner 368
	   |-- adventure-platform-fabric 5.9.0
	   |    |-- net_kyori_adventure-api 4.14.0
	   |    |-- net_kyori_adventure-key 4.14.0
	   |    |-- net_kyori_adventure-platform-api 4.3.0
	   |    |-- net_kyori_adventure-text-logger-slf4j 4.14.0
	   |    |-- net_kyori_adventure-text-minimessage 4.14.0
	   |    |-- net_kyori_adventure-text-serializer-ansi 4.14.0
	   |    |-- net_kyori_adventure-text-serializer-gson 4.14.0
	   |    |-- net_kyori_adventure-text-serializer-json 4.14.0
	   |    |-- net_kyori_adventure-text-serializer-plain 4.14.0
	   |    |-- net_kyori_ansi 1.0.2
	   |    |-- net_kyori_examination-api 1.3.0
	   |    \-- net_kyori_examination-string 1.3.0
	   |-- com_github_llamalad7_mixinextras 0.2.0-beta.9
	   |-- com_github_wdog5_mixin-tools 1.0.1
	   |-- com_mohistmc_i18n 0.2
	   |-- net_fabricmc_mapping-io 0.3.0
	   |-- net_minecrell_terminalconsoleappender 1.4.0
	   |-- org_apache_logging_log4j_log4j-iostreams 2.20.0
	   |-- org_jline_jline-terminal 3.21.0
	   |-- org_jline_jline-terminal-jansi 3.21.0
	   \-- org_yaml_snakeyaml 1.33
	- carpet 1.4.112+v230608
	- fabric-api 0.86.1+1.20.1
	   |-- fabric-api-base 0.4.30+7abfd51577
	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b77
	   |-- fabric-block-api-v1 1.0.9+e022e5d177
	   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
	   |-- fabric-command-api-v1 1.2.33+f71b366f77
	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
	   |-- fabric-commands-v0 0.2.50+df3654b377
	   |-- fabric-containers-v0 0.1.62+df3654b377
	   |-- fabric-content-registries-v0 4.0.9+b3afc78b77
	   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.2.1+1e61dba177
	   |-- fabric-dimensions-v1 2.1.52+b3afc78b77
	   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.1+e91849a877
	   |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a77
	   |-- fabric-item-api-v1 2.1.27+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.10+23d9108177
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
	   |-- fabric-loot-api-v2 1.1.39+b3afc78b77
	   |-- fabric-loot-tables-v1 1.1.43+9e7660c677
	   |-- fabric-message-api-v1 5.1.7+3265161977
	   |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
	   |-- fabric-model-loading-api-v1 1.0.2+709a987177
	   |-- fabric-models-v0 0.4.1+9386d8a777
	   |-- fabric-networking-api-v1 1.3.9+b3afc78b77
	   |-- fabric-networking-v0 0.3.49+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.1+6beca84877
	   |-- fabric-particles-v1 1.1.1+201a23a077
	   |-- fabric-recipe-api-v1 1.0.19+b3afc78b77
	   |-- fabric-registry-sync-v0 2.3.1+4df89eb277
	   |-- fabric-renderer-api-v1 3.1.1+9386d8a777
	   |-- fabric-renderer-indigo 1.4.1+9172968c77
	   |-- fabric-renderer-registries-v1 3.2.45+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.34+b3afc78b77
	   |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
	   |-- fabric-rendering-v0 1.1.48+df3654b377
	   |-- fabric-rendering-v1 3.0.7+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
	   |-- fabric-resource-loader-v0 0.11.9+132c48c177
	   |-- fabric-screen-api-v1 2.0.7+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.28+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.3.0+cdf060b277
	   \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
	- fabricloader 0.14.22
	- java 17
	- logbegone 1.0.8
	- minecraft 1.20.1
	- porting_lib 2.1.1107+1.20-entity-refactor
	   |-- com_electronwill_night-config_core 3.6.6
	   |-- com_electronwill_night-config_toml 3.6.6
	   |-- mm 2.3
	   |-- porting_lib_accessors 2.1.1107+1.20-entity-refactor
	   |-- porting_lib_asm 2.1.1107+1.20-entity-refactor
	   |-- porting_lib_attributes 2.1.1107+1.20-entity-refactor
	   |-- porting_lib_base 2.1.1107+1.20-entity-refactor
	   |-- porting_lib_brewing 2.1.1107+1.20-entity-refactor
	   |-- porting_lib_chunk_loading 2.1.1107+1.20-entity-refactor
	   |-- porting_lib_client_events 2.1.1107+1.20-entity-refactor
	   |-- porting_lib_common 2.1.1107+1.20-entity-refactor
	   |-- porting_lib_config 2.1.1107+1.20-entity-refactor
	   |-- porting_lib_core 2.1.1107+1.20-entity-refactor
	   |-- porting_lib_data 2.1.1107+1.20-entity-refactor
	   |-- porting_lib_entity 2.1.1107+1.20-entity-refactor
	   |-- porting_lib_extensions 2.1.1107+1.20-entity-refactor
	   |-- porting_lib_fluids 2.1.1107+1.20-entity-refactor
	   |-- porting_lib_gametest 2.1.1107+1.20-entity-refactor
	   |-- porting_lib_lazy_registration 2.1.1107+1.20-entity-refactor
	   |-- porting_lib_loot 2.1.1107+1.20-entity-refactor
	   |-- porting_lib_mixin_extensions 2.1.1107+1.20-entity-refactor
	   |-- porting_lib_model_builders 2.1.1107+1.20-entity-refactor
	   |-- porting_lib_model_generators 2.1.1107+1.20-entity-refactor
	   |-- porting_lib_model_loader 2.1.1107+1.20-entity-refactor
	   |-- porting_lib_model_materials 2.1.1107+1.20-entity-refactor
	   |-- porting_lib_models 2.1.1107+1.20-entity-refactor
	   |-- porting_lib_networking 2.1.1107+1.20-entity-refactor
	   |-- porting_lib_obj_loader 2.1.1107+1.20-entity-refactor
	   |-- porting_lib_recipe_book_categories 2.1.1107+1.20-entity-refactor
	   |-- porting_lib_registries 2.1.1107+1.20-entity-refactor
	   |-- porting_lib_tags 3.0
	   |-- porting_lib_tool_actions 2.1.1107+1.20-entity-refactor
	   |-- porting_lib_transfer 2.1.1107+1.20-entity-refactor
	   \-- porting_lib_utility 2.1.1107+1.20-entity-refactor
	- spark 1.10.42
	   \-- fabric-permissions-api-v0 0.1-SNAPSHOT
[00:53:25] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/D:/Server/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[00:53:25] [main/INFO]: Compatibility level set to JAVA_17
[00:53:26] [main/INFO]:  _____       ___   __   _   __   _   _____   _____   
[00:53:26] [main/INFO]: |  _  \     /   | |  \ | | |  \ | | | ____| |  _  \  
[00:53:26] [main/INFO]: | |_| |    / /| | |   \| | |   \| | | |__   | |_| |  
[00:53:26] [main/INFO]: |  _  {   / / | | | |\   | | |\   | |  __|  |  _  /  
[00:53:26] [main/INFO]: | |_| |  / /  | | | | \  | | | \  | | |___  | | \ \  
[00:53:26] [main/INFO]: |_____/ /_/   |_| |_|  \_| |_|  \_| |_____| |_|  \_\ 
[00:53:26] [main/INFO]: Welcome to Banner 1.20.1! - Mohist Developement Group - 368, Java 61.0
[00:53:29] [main/INFO]: Injecting into root logger...
[00:53:29] [main/WARN]: By enabling mojang mappings, you agree to their license:
[00:53:29] [main/WARN]: (c) 2020 Microsoft Corporation.These mappings are provided "as-is" and you bear the risk of using them.
[00:53:29] [main/WARN]: You may copy and use the mappings for development purposes, but you may not redistribute the mappings complete and unmodified.
[00:53:29] [main/WARN]: Microsoft makes no warranties, express or implied, with respect to the mappings provided here.
[00:53:29] [main/WARN]: Use and modification of this document or the source code (in any form) of Minecraft: Java Edition is governed by
[00:53:29] [main/WARN]: the Minecraft End User License Agreement available at https://account.mojang.com/documents/minecraft_eula.
[00:53:29] [main/INFO]: Creating asynchronous mapping cache executor...
[00:53:29] [Mappings Cache Thread/INFO]: Verifying cache of mojang mappings...
[00:53:29] [Mappings Cache Thread/INFO]: Verified cache of mojang mappings (took 1ms)
[00:53:29] [Mappings Cache Thread/INFO]: Parsing mojang mappings...
[00:53:30] [main/WARN]: Reference map 'porting_lib_obj_loader-refmap.json' for porting_lib_obj_loader.mixins.json could not be read. If this is a development environment you can ignore this message
[00:53:35] [main/WARN]: Error loading class: net/minecraft/class_757 (java.lang.ClassNotFoundException: net/minecraft/class_757)
[00:53:35] [main/WARN]: @Mixin target net.minecraft.class_757 was not found mixins.mm.json:net.minecraft.class_757 from mod mm
[00:53:37] [Mappings Cache Thread/INFO]: Parsed mojang mappings (took 7944ms)
[00:53:37] [Mappings Cache Thread/INFO]: Caching mojang mappings...
[00:53:38] [Mappings Cache Thread/INFO]: Cached mojang mappings (took 377ms)
[00:53:38] [Mappings Cache Thread/INFO]: Cached mappings have been built (took 8426ms)
[00:53:38] [Mappings Cache Thread/INFO]:  Classes: 4945
[00:53:38] [Mappings Cache Thread/INFO]:  Methods: 26367
[00:53:38] [Mappings Cache Thread/INFO]:  Fields: 23166
[00:53:38] [ForkJoinPool.commonPool-worker-1/INFO]: Shutting down asynchronous mapping cache executor...
[00:53:38] [ForkJoinPool.commonPool-worker-1/INFO]: Loading libraries, please wait...
[00:53:40] [main/WARN]: Invalid registry value type detected for PerfOS counters. Should be REG_DWORD. Ignoring: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PerfOS\Performance\Disable Performance Counters.
[00:53:41] [main/ERROR]: Mixin apply for mod porting_lib_base failed porting_lib_base.mixins.json:common.LivingEntityMixin from mod porting_lib_base -> net.minecraft.world.entity.LivingEntity: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/world/entity/LivingEntity::port_lib$addEffect with priority 500 cannot inject into net/minecraft/world/entity/LivingEntity::addEffect(Lnet/minecraft/world/effect/MobEffectInstance;Lnet/minecraft/world/entity/Entity;)Z merged by com.mohistmc.banner.mixin.world.entity.MixinLivingEntity with priority 500 [PREINJECT Applicator Phase -> porting_lib_base.mixins.json:common.LivingEntityMixin from mod porting_lib_base -> Prepare Injections ->  -> handler$zck000$porting_lib_base$port_lib$addEffect(Lnet/minecraft/world/effect/MobEffectInstance;Lnet/minecraft/world/entity/Entity;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/world/effect/MobEffectInstance;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/world/entity/LivingEntity::port_lib$addEffect with priority 500 cannot inject into net/minecraft/world/entity/LivingEntity::addEffect(Lnet/minecraft/world/effect/MobEffectInstance;Lnet/minecraft/world/entity/Entity;)Z merged by com.mohistmc.banner.mixin.world.entity.MixinLivingEntity with priority 500 [PREINJECT Applicator Phase -> porting_lib_base.mixins.json:common.LivingEntityMixin from mod porting_lib_base -> Prepare Injections ->  -> handler$zck000$porting_lib_base$port_lib$addEffect(Lnet/minecraft/world/effect/MobEffectInstance;Lnet/minecraft/world/entity/Entity;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/world/effect/MobEffectInstance;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1337) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.SystemReport.handler$cfb000$carpet$fillSystemDetails(SystemReport.java:521) ~[server-intermediary.jar:?]
	at net.minecraft.SystemReport.<init>(SystemReport.java:58) ~[server-intermediary.jar:?]
	at net.minecraft.CrashReport.<init>(CrashReport.java:34) ~[server-intermediary.jar:?]
	at net.minecraft.CrashReport.preload(CrashReport.java:274) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:102) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.22.jar:?]
[00:53:41] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Mixin transformation of net.minecraft.world.entity.LivingEntity failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.SystemReport.handler$cfb000$carpet$fillSystemDetails(SystemReport.java:521) ~[server-intermediary.jar:?]
	at net.minecraft.SystemReport.<init>(SystemReport.java:58) ~[server-intermediary.jar:?]
	at net.minecraft.CrashReport.<init>(CrashReport.java:34) ~[server-intermediary.jar:?]
	at net.minecraft.CrashReport.preload(CrashReport.java:274) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:102) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.22.jar:?]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.22.jar:?]
	... 21 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [porting_lib_base.mixins.json:common.LivingEntityMixin from mod porting_lib_base] from phase [DEFAULT] in config [porting_lib_base.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.22.jar:?]
	... 21 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/world/entity/LivingEntity::port_lib$addEffect with priority 500 cannot inject into net/minecraft/world/entity/LivingEntity::addEffect(Lnet/minecraft/world/effect/MobEffectInstance;Lnet/minecraft/world/entity/Entity;)Z merged by com.mohistmc.banner.mixin.world.entity.MixinLivingEntity with priority 500 [PREINJECT Applicator Phase -> porting_lib_base.mixins.json:common.LivingEntityMixin from mod porting_lib_base -> Prepare Injections ->  -> handler$zck000$porting_lib_base$port_lib$addEffect(Lnet/minecraft/world/effect/MobEffectInstance;Lnet/minecraft/world/entity/Entity;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/world/effect/MobEffectInstance;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1337) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.22.jar:?]
	... 21 more

**Comment by windy664** [comment]
同问 不然根源魔法、机械动力玩不了

**Comment by windy664** [comment]
匠魂出.120fabric了 这个不兼容玩不了。

**Comment by Mgazul** [comment]
经过测试porting_lib-2.1.1115+1.20-entity-refactor无该问题

**Comment by windy664** [comment]
Banner 485 ， portlib崩溃 
[crash-2023-10-22_12.33.08-server.txt](https://github.com/MohistMC/Banner/files/13062374/crash-2023-10-22_12.33.08-server.txt)
