### ISSUE TITLE
多世界另一维度的漏斗导致开服后就崩溃

### ISSUE THREAD

**Issue by PrisamaX0124** [MohistMC/Banner#130]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

banner-1.20.1-376.jar

### Java 版本 | 操作系统

系统：Windows 10 x64/Dragonwell JDK 17.0.5.0.5

### 相关 Mod/插件 的名称及版本

```raw
Multiverse-Core-4.3.1.jar
```

### 错误描述

已经将存档拉进单人存档清除掉了第一个有问题的漏斗，然后再将存档转移到服务器里再次开服，但又是另一个漏斗引起了问题。另外暂时回到356版本后没有这个问题。

### 复现步骤

1.将banner从1.20.1-356更新至1.20.1-376
2.正常启动服务器，任何mod、插件或参数都未改变
3.开服完毕，所有维度加载完成之后马上因为Ticking Entity报错
4.服务器自动关闭

### 报错信息

[07:49:57] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:901) ~[server-intermediary.jar:?]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:824) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bod000$carpet$modifiedRunLoop(MinecraftServer.java:8430) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:2090) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.event.inventory.InventoryMoveItemEvent.isCancelled()" because the return value of "java.util.concurrent.atomic.AtomicReference.get()" is null
	at net.minecraft.world.level.block.entity.HopperBlockEntity.handler$bjl000$banner$cancelIfNotEject(HopperBlockEntity.java:630) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.ejectItems(HopperBlockEntity.java:153) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.ejectItems(HopperBlockEntity.java:596) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.redirect$bjl000$banner$changeEjects(HopperBlockEntity.java:586) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.tryMoveItems(HopperBlockEntity.java:115) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.redirect$bjl000$banner$hopperCheck(HopperBlockEntity.java:568) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.pushItemsTick(HopperBlockEntity.java:102) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.redirect$bog000$carpet$checkProcessBEs(LevelChunk.java:1290) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:662) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:716) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.Level.tickBlockEntities(Level.java:470) ~[server-intermediary.jar:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:390) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:897) ~[server-intermediary.jar:?]
	... 6 more
[07:49:57] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.NullPointerException: Cannot invoke "org.bukkit.event.inventory.InventoryMoveItemEvent.isCancelled()" because the return value of "java.util.concurrent.atomic.AtomicReference.get()" is null
	at net.minecraft.world.level.block.entity.HopperBlockEntity.handler$bjl000$banner$cancelIfNotEject(HopperBlockEntity.java:630) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.ejectItems(HopperBlockEntity.java:153) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.ejectItems(HopperBlockEntity.java:596) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.redirect$bjl000$banner$changeEjects(HopperBlockEntity.java:586) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.tryMoveItems(HopperBlockEntity.java:115) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.redirect$bjl000$banner$hopperCheck(HopperBlockEntity.java:568) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.pushItemsTick(HopperBlockEntity.java:102) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.redirect$bog000$carpet$checkProcessBEs(LevelChunk.java:1290) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:662) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:716) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.Level.tickBlockEntities(Level.java:470) ~[server-intermediary.jar:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:390) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:897) ~[server-intermediary.jar:?]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:824) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bod000$carpet$modifiedRunLoop(MinecraftServer.java:8430) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:2090) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Mgazul** [comment]
Fixed
