### ISSUE TITLE
Itemsadder plugin not working(works half.)

### ISSUE THREAD

**Issue by sj-hub9796** [MohistMC/Banner#146]
### I have confirmed that ...

- [X] Banner is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Fabric

### Banner version

banner 401

### OS & Java versions

openjdk version "17.0.7" 2023-04-18

### Plugins and Mods

```raw
Plugins (3): LoneLibs, ProtocolLib, ItemsAdder
Mods: adventure-platform-fabric, Banner Mod, MixinExtras, mixin-tools, i18n, Fabric API, Fabric Convention Tags, Fabric Loader, OpenJDK, mapping-io, adventure-api, adventure-key, adventure-platform-api, adventure-text-logger-slf4j, adventure-text-minimessage, adventure-text-serializer-ansi, adventure-text-serializer-gson, adventure-text-serializer-json, adventure-text-serializer-plain, examination-api, examination-string, terminalconsoleappender, log4j-iostreams, jline-terminal, jline-terminal-jansi, snakeyaml
```

### Description

Itemsadder commands are mostly not working(some commands worked). and lot of console spam.

### Step to reproduce

1. install Itemsadder 3.5.0c-r4 version and protocollib, lonelib
2. start the server
3. you can see lot of spam in console and commands mostly not working

### Logs

[2023-08-18-5.log](https://github.com/MohistMC/Banner/files/12380635/2023-08-18-5.log)

**Comment by windy664** [comment]
`[10:27:26] [Server thread/ERROR]: Could not pass event FurnaceBurnEvent to ItemsAdder v3.5.0c-r2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:307) ~[Banner-1.20-1.20.1-411.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:75) ~[Banner-1.20-1.20.1-411.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:604) ~[Banner-1.20-1.20.1-411.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:591) ~[Banner-1.20-1.20.1-411.jar:?]
        at net.minecraft.world.level.block.entity.AbstractFurnaceBlockEntity.eject$cca000$banner$setBurnTime(AbstractFurnaceBlockEntity.java:674) ~[server-intermediary.jar:?]
        at net.minecraft.world.level.block.entity.AbstractFurnaceBlockEntity.serverTick(AbstractFurnaceBlockEntity.java:317) ~[server-intermediary.jar:?]
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:662) ~[server-intermediary.jar:?]
        at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:716) ~[server-intermediary.jar:?]
        at net.minecraft.world.level.Level.tickBlockEntities(Level.java:470) ~[server-intermediary.jar:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:390) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:897) ~[server-intermediary.jar:?]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:2133) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'boolean net.minecraft.world.item.ItemStack.u()'
        at ia.nms.nbt.nms.impl.CraftItemStack_v1_20_R1.u(SourceFile:51) ~[?:?]
        at ia.nms.nbt.NItem.t(SourceFile:65) ~[?:?]
        at ia.m.er.isCustomItem(SourceFile:259) ~[?:?]
        at ia.m.G.a(SourceFile:3119) ~[?:?]
        at ia.m.G.a(SourceFile:3150) ~[?:?]
        at ia.m.bK.a(SourceFile:42) ~[?:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[Banner-1.20-1.20.1-411.jar:?]
        ... 15 more`
