### ISSUE TITLE
Quickshop Packet Display Issue

### ISSUE THREAD

**Issue by VOrlando520** [MohistMC/Banner#187]
### I have confirmed that ...

- [X] Banner is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Fabric

### Banner version

Banner version 1.20.1-474

### OS & Java versions

OS: Debian 11 Java: Java17

### Plugins and Mods

```raw
Fabric
Banner
CMI
Vault
ProtocolLib
Quickshop
```

### Description

On server startup, the display-type falls back to a default (laggier) method because of a missing class that is listed in the log below.

### Step to reproduce

Install Quickshop
Set display-type to 2 in config
Restart
Look in console for error

### Logs

[[02:08:13] [Server thread/ERROR]: [QuickShop] Virtual DisplayItem Support Test: Failed to initialize VirtualDisplayItem
java.lang.NullPointerException: Unable to create packet instance for class class net.minecraft.network.protocol.game.ClientboundAddEntityPacket
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at com.comphenix.protocol.injector.StructureCache.lambda$newPacket$2(StructureCache.java:99) ~[?:?]
        at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:103) ~[?:?]
        at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:113) ~[?:?]
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:117) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.createPacket(PacketFilterManager.java:389) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.createPacket(PacketFilterManager.java:384) ~[?:?]
        at org.maxgamer.quickshop.shop.VirtualDisplayItem$PacketFactory.createFakeItemSpawnPacket(VirtualDisplayItem.java:370) ~[?:?]
        at org.maxgamer.quickshop.shop.VirtualDisplayItem$PacketFactory.testFakeItem(VirtualDisplayItem.java:358) ~[?:?]
        at org.maxgamer.quickshop.util.envcheck.EnvironmentChecker.virtualDisplaySupportTest(EnvironmentChecker.java:428) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.maxgamer.quickshop.util.envcheck.EnvironmentChecker.run(EnvironmentChecker.java:123) ~[?:?]
        at org.maxgamer.quickshop.QuickShop.runtimeCheck(QuickShop.java:869) ~[?:?]
        at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:961) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[banner-1.20.1-474.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) ~[banner-1.20.1-474.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482) ~[banner-1.20.1-474.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:534) ~[banner-1.20.1-474.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:456) ~[banner-1.20.1-474.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zck000$banner$enablePlugins(MinecraftServer.java:2252) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:339) ~[server-intermediary.jar:?]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:169) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:2083) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]](https://pastebin.com/xaK9tvD5)

**Comment by windy664** [comment]
I am using Quickshop 5.1.2.4, in which I haven't encountered this issue
