### ISSUE TITLE
添加无plugin的banner后服务端无法启动

### ISSUE THREAD

**Issue by charliez0** [MohistMC/Banner#213]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

524

### Java 版本 | 操作系统

Windows Java(TM) SE Runtime Environment Oracle GraalVM 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19)

### 相关 Mod/插件 的名称及版本

```raw
Ad-Astra-Giselle-Addon-fabric-1.20.1-5.6.jar
 Adorn-5.0.1+1.20.1-fabric.jar
 AdvancedReborn-1.20-1.2.1.jar
 Applied-Botanics-fabric-1.5.0.jar
 Aquamirae+6.jar
 BambooEverything-fabric-3.0.3+mc1.20.1.jar
 BeaconOverhaul-1.8.4+1.20.jar
 Bookshelf-Fabric-1.20.1-20.1.8.jar
 Botania-1.20.1-443-FABRIC.jar
 Chunky-1.3.92.jar
 CorgiLib-fabric-1.20.1-4.0.0.4.jar
 Croptopia-1.20.1-FABRIC-3.0.4.jar
 CroptopiaAdditions-1.20.1-FABRIC-2.0.jar
 EpheroLib-1.20.1-FABRIC-1.2.0.jar
 Farmersrespite-Fabric-2.3.4.jar
 ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar
 Modern-Industrialization-1.8.0.jar
 ModernUI-Fabric-1.20.1-3.9.0.4-universal.jar
 NethersDelight-1.0.0.jar
 Obscure-API-16.jar
 Patchouli-1.20.1-84-FABRIC.jar
 Powah-5.0.4.jar
 Prism-1.20.1-fabric-1.0.5.jar
 RebornCore-5.8.7.jar
 RoughlyEnoughItems-12.0.684-fabric.jar
 SWPlanets-fabric-1.20.1-1.2.2.jar
 Steam_Rails-1.5.1+fabric-mc1.20.1.jar
 Structory_1.20.2_v1.3.4.jar
 TechReborn-5.8.7.jar
 Terra-fabric-6.3.1-BETA+73baaec6c.jar
 TerraBlender-fabric-1.20.1-3.0.1.2.jar
 Terralith_1.20.4_v2.4.11.jar
 WWOO-FABRIC+FORGE+QUILT-2.0.0.jar
 YeetusExperimentus-Fabric-2.3.1-build.6+mc1.20.1.jar
'[manual]LMML-1.20.1-8.0.1-Fabric.jar'
'[manual]LMRB-1.20.1-8.2.0-Fabric.jar'
'[server]FabricProxy-Lite-2.6.0.jar'
'[server]LuckPerms-Fabric-5.4.102.jar'
'[server]banner-1.20.1-524.jar'
'[server]logprot-fabric-1.20.1-3.3.jar'
'[server]mclogs-fabric-1.4.1-1.20.jar'
'[server]respawndelay-1.20.1-4.4.jar'
'[server]smoothchunk-fabric-1.20.1-3.5.jar'
'[server]vanilla-permissions-0.2.2+1.20.1.jar'
 ad_astra-fabric-1.20.1-1.15.5.jar
 additionallanterns-1.1.1-fabric-mc1.20.jar
 ae2wtlib-15.2.1-fabric.jar
 alloy-forgery-2.1.2+1.20.jar
 amethyst_core-1.4.5+1.20.1.jar
 amethyst_imbuement-1.20.1-18.jar
 anvilrestoration-1.20.1-2.2.jar
 appliedenergistics2-fabric-15.0.19.jar
 architectury-9.1.12-fabric.jar
 artifacts-fabric-9.2.0.jar
 autoconfig1u-3.4.0.jar
 automaticdoors-1.20.1-4.6.jar
 avaritia-0.6.jar
 bclib-3.0.14.jar
 beaconsforall-fabric-6.2.1+1.20.1.jar
 better-end-4.0.11.jar
 better-nether-9.0.10.jar
 betterbeaconplacement-1.20.1-3.3.jar
 betterfpsdist-fabric-1.20.1-4.0.jar
 botarium-fabric-1.20.1-2.3.1.jar
 bottledair-1.20.1-2.3.jar
 brewinandchewin-fabric-2.3.2+1.20.1.jar
 bwncr-fabric-1.20.1-3.17.0.jar
 cc-tweaked-1.20.1-fabric-1.109.3.jar
 chefs-delight-1.0.3-fabric-1.20.1.jar
 clickadv-fabric-1.20.1-3.7.jar
 cloth-config-11.1.118-fabric.jar
 collective-1.20.1-7.30.jar
 comforts-fabric-6.3.4+1.20.1.jar
 compacthelpcommand-1.20.1-2.5.jar
 crawl-0.12.0.jar
 create-fabric-0.5.1-d-build.11+mc1.20.1.jar
 create-new-age-fabric-1.20.1-1.1.1.jar
 createaddition-fabric+1.20.1-0.9.0.jar
 createutilities-0.1.3b+1.20.1.jar
 cristellib-1.1.5-fabric.jar
 cultural-delights-fabric-0.14.11+1.20.1.jar
 cupboard-fabric-1.20.1-2.2.jar
 dawn-5.0.0.jar
 delightful-creators-1.1.8.jar
 diet-fabric-2.1.1+1.20.1.jar
 doapi-1.2.8-fabric.jar
 ends_delight-fabric-1.20.1-1.0.1.jar
 entangled-1.3.16-fabric-mc1.20.jar
 expanded_ecosphere-3.2.4-fabric.jar
 expandeddelight-0.3.0.2.jar
 fabric-api-0.91.0+1.20.1.jar
 fabric-language-kotlin-1.10.17+kotlin.1.9.22.jar
 fabric-seasons-2.3+1.20.jar
 fabric-seasons-croptopia-2.2.2-compat-1.0.jar
 fabric-seasons-delight-1.3.9-compat-1.0.jar
 fabric-seasons-extras-1.2-BETA+1.20.jar
 fabric-seasons-terralith-2.3.7-compat-1.0.jar
 farmers-delight-fabric-1.4.3.jar
 ferritecore-6.0.1-fabric.jar
 findme-3.2.0-fabric.jar
 flatbedrock-fabric-3.0.1-build.18+mc1.20.1.jar
 framework-fabric-1.20.1-0.6.16.jar
 frightsdelight-1.20.1-1.0.1.jar
 ftb-chunks-fabric-2001.2.5.jar
 ftb-essentials-fabric-2001.2.2.jar
 ftb-filter-system-fabric-1.0.2.jar
 ftb-library-fabric-2001.1.4.jar
 ftb-quests-fabric-2001.3.0.jar
 ftb-ranks-fabric-2001.1.3.jar
 ftb-teams-fabric-2001.1.4.jar
 ftb-ultimine-fabric-2001.1.4.jar
 ftb-xmod-compat-fabric-2.1.0.jar
 ftbbackups2-fabric-1.20-1.0.23.jar
 fulleng-fabric-1.6-1.20.1.jar
 fzzy_core-0.3.4+1.20.1.jar
 geckolib-fabric-1.20.1-4.4.jar
 goblintraders-fabric-1.20.1-1.9.3.jar
 handoveryouritems-1.20.1-3.2.jar
 immersive_aircraft-0.6.2+1.20.1-fabric.jar
 immersive_armors-1.6.1+1.20.1-fabric.jar
 immersive_melodies-0.1.0+1.20.1-fabric.jar
 immersive_paintings-0.6.7+1.20.1-fabric.jar
 indrez-1.16.5-BETA-Hotfix.jar
 iron-jetpacks-0.4.7.jar
 krypton-0.2.3.jar
 letsdo-bakery-fabric-1.1.3b.jar
 letsdo-beachparty-fabric-1.1.3.jar
 letsdo-candlelight-fabric-1.2.8.jar
 letsdo-herbalbrews-fabric-1.0.2.jar
 letsdo-nethervinery-fabric-1.2.2.jar
 letsdo-vinery-1.4.7-fabric.jar
 litematica-fabric-1.20.1-0.15.3.jar
 lithium-fabric-mc1.20.1-0.11.2.jar
 malilib-fabric-1.20.1-0.16.3.jar
 mcpitanlibarch-1.8.5-1.20.4-fabric.jar
 merequester-fabric-1.20.1-1.1.4.jar
 modernfix-fabric-5.12.1+mc1.20.1.jar
 modmenu-7.2.2.jar
 moveboats-1.20.1-3.2.jar
 moveminecarts-1.20.1-3.4.jar
 naturalist-fabric-4.0.3-1.20.1.jar
 nbtedit-fabric-5.0.1.jar
 nerb-1.20.1-0.3-FABRIC.jar
 observable-4.4.0.jar
 oceansdelight-fabric-1.0.2-1.20.jar
 owo-lib-0.11.2+1.20.jar
 placeableblazerods-1.20.1-3.4.jar
 polyeng-fabric-0.1.0-1.20.1.jar
 polymorph-fabric-0.49.1+1.20.1.jar
 promenade-4.1.1.jar
 randomsheepcolours-1.20.1-3.3.jar
 randomshulkercolours-1.20.1-3.2.jar
 reinforced-chests-2.4.2+1.20.jar
 resourcefulconfig-fabric-1.20.1-2.1.2.jar
 resourcefullib-fabric-1.20.1-2.1.20.jar
 respawnablepets-1.20-1.jar
 revelationary-1.3.6+1.20.1.jar
 spectrum-1.7.4-deeper-down.jar
 spectrum-jetpacks-1.0.3+1.20.1.jar
 stackrefill-1.20.1-4.2.jar
 starlight-1.1.2+fabric.dbc156f.jar
 supermartijn642configlib-1.1.8a-fabric-mc1.20.jar
 supermartijn642corelib-1.1.16-fabric-mc1.20.1.jar
 things-0.3.3+1.20.jar
 travelers-backpack-1.20.1-9.1.9.jar
 trinkets-3.7.1.jar
 velocity-3.3.0-SNAPSHOT-320.jar
 villagebellrecipe-1.20.1-3.2.jar
 windchimes-1.2.4+1.20.jar
 wooltweaks-1.20.1-3.3.jar
 worldedit-mod-7.2.15.jar
 yesstevemodel-1.20-fabric-release-1.1.5-hotfix-2.jar
 yuushya-1.20.1-fabric-2.1.1.jar
 yuushya-modelling-1.20.1-fabric-2.0.0.jar
```

### 错误描述

无banner的情况可以正常启动服务器，添加没有plugins的banner后服务器无法启动

### 报错信息

```plain
[23:34:27] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'ad_astra'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.4.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.4.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.4.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.4.jar:?]
        at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.4.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.4.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.4.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.4.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.15.4-launcher.1.0.0.jar:1.0.0]
        Suppressed: java.lang.NoClassDefFoundError: Could not initialize class earth.terrarium.ad_astra.common.registry.ModEntityTypes
                at earth.terrarium.ad_astra.common.registry.ModItems.<clinit>(ModItems.java:407) ~[ad_astra-fabric-1.20.1-1.15.5.jar:?]
                at earth.terrarium.ad_astra.AdAstra.postInit(AdAstra.java:49) ~[ad_astra-fabric-1.20.1-1.15.5.jar:?]
                at java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:199) ~[?:?]
                at com.sun.proxy.jdk.proxy3.$Proxy34.onInitialize(Unknown Source) ~[?:?]
                at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.4.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.4.jar:?]
                at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.4.jar:?]
                at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.4.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.4.jar:?]
                at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.4.jar:?]
                at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.15.4-launcher.1.0.0.jar:1.0.0]
        Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IncompatibleClassChangeError: class earth.terrarium.ad_astra.common.entity.mob.SulfurCreeper overrides final method net.minecraft.class_1548.method_7006()V [in thread "main"]
                at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
                at java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
                at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.4.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.4.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.4.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.4.jar:?]
                at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
                at earth.terrarium.ad_astra.common.registry.ModEntityTypes.lambda$static$10(ModEntityTypes.java:37) ~[ad_astra-fabric-1.20.1-1.15.5.jar:?]
                at com.teamresourceful.resourcefullib.common.registry.fabric.FabricRegistryEntry.of(FabricRegistryEntry.java:20) ~[resourcefullib-fabric-1.20.1-2.1.20.jar:?]
                at com.teamresourceful.resourcefullib.common.registry.fabric.FabricResourcefulRegistry.register(FabricResourcefulRegistry.java:25) ~[resourcefullib-fabric-1.20.1-2.1.20.jar:?]
                at earth.terrarium.ad_astra.common.registry.ModEntityTypes.<clinit>(ModEntityTypes.java:37) ~[ad_astra-fabric-1.20.1-1.15.5.jar:?]
                at earth.terrarium.ad_astra.AdAstra.init(AdAstra.java:27) ~[ad_astra-fabric-1.20.1-1.15.5.jar:?]
                at earth.terrarium.ad_astra.fabric.AdAstraFabric.init(AdAstraFabric.java:24) ~[ad_astra-fabric-1.20.1-1.15.5.jar:?]
                ... 10 more
        Suppressed: java.lang.IncompatibleClassChangeError: class fr.hugman.promenade.entity.LushCreeperEntity overrides final method net.minecraft.class_1548.method_7006()V
                at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
                at java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
                at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.4.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.4.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.4.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.4.jar:?]
                at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
                at fr.hugman.promenade.registry.content.MonsterContent.<clinit>(MonsterContent.java:23) ~[promenade-4.1.1.jar:?]
                at fr.hugman.promenade.Promenade.onInitialize(Promenade.java:28) ~[promenade-4.1.1.jar:?]
                at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.4.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.4.jar:?]
                at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.4.jar:?]
                at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.4.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.4.jar:?]
                at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.4.jar:?]
                at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.15.4-launcher.1.0.0.jar:1.0.0]
Caused by: java.lang.IncompatibleClassChangeError: class earth.terrarium.ad_astra.common.entity.mob.SulfurCreeper overrides final method net.minecraft.class_1548.method_7006()V
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.4.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.4.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.4.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.4.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at earth.terrarium.ad_astra.common.registry.ModEntityTypes.lambda$static$10(ModEntityTypes.java:37) ~[ad_astra-fabric-1.20.1-1.15.5.jar:?]
        at com.teamresourceful.resourcefullib.common.registry.fabric.FabricRegistryEntry.of(FabricRegistryEntry.java:20) ~[resourcefullib-fabric-1.20.1-2.1.20.jar:?]
        at com.teamresourceful.resourcefullib.common.registry.fabric.FabricResourcefulRegistry.register(FabricResourcefulRegistry.java:25) ~[resourcefullib-fabric-1.20.1-2.1.20.jar:?]
        at earth.terrarium.ad_astra.common.registry.ModEntityTypes.<clinit>(ModEntityTypes.java:37) ~[ad_astra-fabric-1.20.1-1.15.5.jar:?]
        at earth.terrarium.ad_astra.AdAstra.init(AdAstra.java:27) ~[ad_astra-fabric-1.20.1-1.15.5.jar:?]
        at earth.terrarium.ad_astra.fabric.AdAstraFabric.init(AdAstraFabric.java:24) ~[ad_astra-fabric-1.20.1-1.15.5.jar:?]
        at java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:199) ~[?:?]
        at com.sun.proxy.jdk.proxy3.$Proxy34.onInitialize(Unknown Source) ~[?:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.4.jar:?]
        ... 7 more
```

**Comment by wdog5** [comment]
The issues is caused by mod about ad_astra
