### ISSUE TITLE
Joining throws an ERROR stating that `this.authenticatedProfile` is null

### ISSUE THREAD

**Issue by EW2010** [MohistMC/Banner#217]
### I have confirmed that ...

- [X] Banner is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Fabric

### Banner version

1.20.4

### OS & Java versions

OS Windows-64Bit, Java openjdk version "20.0.2" 2023-07-18

### Plugins and Mods

```raw
-
```

### Description

this error definitly shouldn't appear:
```
java.lang.NullPointerException: Cannot invoke "com.mojang.authlib.GameProfile.getName()" because "this.authenticatedProfile" is null
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.banner$preLogin(ServerLoginPacketListenerImpl.java:658) ~[server-intermediary.jar:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl$Anonymous$81db94f27ff64a1b9989b97701e79e0d.run(MixinServerLoginPacketListenerImpl.java:147) ~[?:?]
stop
```

### Step to reproduce

1. Join the game
2. check the logs

### Logs

```
java.lang.NullPointerException: Cannot invoke "com.mojang.authlib.GameProfile.getName()" because "this.authenticatedProfile" is null
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.banner$preLogin(ServerLoginPacketListenerImpl.java:658) ~[server-intermediary.jar:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl$Anonymous$81db94f27ff64a1b9989b97701e79e0d.run(MixinServerLoginPacketListenerImpl.java:147) ~[?:?]
stop
```

**Comment by EW2010** [comment]
https://github.com/MohistMC/Banner/blob/1f89e0f2655027e0cdff2d089276c65f2a34ff0a/src/main/java/com/mohistmc/banner/mixin/server/network/MixinServerLoginPacketListenerImpl.java#L147

**Comment by wdog5** [comment]
Fixed
