### ISSUE TITLE
Unable to start/create server

### ISSUE THREAD

**Issue by SavageTheUnicorn** [MohistMC/Banner#249]
### I have confirmed that ...

- [X] Banner is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Fabric

### Banner version

639

### OS & Java versions

Ubuntu 22.04 ARM64 & Java 17

### Plugins and Mods

```raw
Banner
FabricApi 0.92.1
```

### Description

2024-04-30 03:08:23,111 main ERROR An exception occurred processing Appender StackDeobfAppender java.lang.IllegalArgumentException: Illegal group reference
        at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1067)
        at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:997)
        at java.base/java.util.regex.Matcher.replaceAll(Matcher.java:1259)
        at com.mohistmc.banner.stackdeobf.mappings.RemappingUtil.remapClasses(RemappingUtil.java:18)
        at com.mohistmc.banner.stackdeobf.mappings.RemappingUtil.remapStackTraceElement(RemappingUtil.java:117)
        at com.mohistmc.banner.stackdeobf.util.Log4jRemapUtil.remapThrowableProxy(Log4jRemapUtil.java:42)
        at com.mohistmc.banner.stackdeobf.util.Log4jRemapUtil.remapThrowableProxy(Log4jRemapUtil.java:48)
        at com.mohistmc.banner.stackdeobf.util.RemappingRewritePolicy.rewrite(RemappingRewritePolicy.java:61)
        at org.apache.logging.log4j.core.appender.rewrite.RewriteAppender.append(RewriteAppender.java:81)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:683)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:641)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:624)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:560)
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
        at org.apache.logging.log4j.core.Logger.log(Logger.java:162)
        at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2017)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1983)
        at org.apache.logging.log4j.spi.AbstractLogger.log(AbstractLogger.java:1662)
        at net.fabricmc.loader.impl.game.minecraft.Log4jLogHandler.log(Log4jLogHandler.java:51)
        at net.fabricmc.loader.impl.util.log.Log.log(Log.java:219)
        at net.fabricmc.loader.impl.util.log.Log.log(Log.java:133)
        at net.fabricmc.loader.impl.util.log.Log.error(Log.java:75)
        at net.fabricmc.loader.impl.launch.FabricLauncherBase.handleFormattedException(FabricLauncherBase.java:79)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)

### Step to reproduce

Add Banner and FabricAPI to barebones Fabric install.

**Comment by Mgazul** [comment]
Fixed
