### ISSUE TITLE
LuckPerms登录错误

### ISSUE THREAD

**Issue by kxkl2077** [MohistMC/Banner#251]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

banner-1.20.1-580-server

### Java 版本 | 操作系统

CentOS7.6

### 相关 Mod/插件 的名称及版本

```raw
fabricmods
fabric-api-0.92.0+1.20.1.jar
banner-1.20.1-580-server.jar

plugins
Luckperms最新版
TrChat最新版
```

### 错误描述

![56895b80f40af6dc09e9dc25de00b681](https://github.com/MohistMC/Banner/assets/110510729/e807d6f7-be0a-4e4f-9f55-797da93af298)

### 复现步骤

1.服务器启动
2.服务器启动成功
3.玩家进入，退出
4.玩家进入，Luckperms报错

### 报错信息

[20:03:44] [Server thread/WARN]: [LuckPerms] User 67b91558-f5fe-36d4-8dd9-6d4ae3cff1e7 - linghao doesn't currently have data pre-loaded, but they have been processed before in this session. - denying login.
[20:03:44] [Server thread/ERROR]: Could not pass event PlayerLoginEvent to TrChat v2.1.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:307) ~[%5B%E6%8F%92%E4%BB%B6%E6%94%AF%E6%8C%81%5Dbanner-1.20.1-580-server.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:75) ~[%5B%E6%8F%92%E4%BB%B6%E6%94%AF%E6%8C%81%5Dbanner-1.20.1-580-server.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:604) ~[%5B%E6%8F%92%E4%BB%B6%E6%94%AF%E6%8C%81%5Dbanner-1.20.1-580-server.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:591) ~[%5B%E6%8F%92%E4%BB%B6%E6%94%AF%E6%8C%81%5Dbanner-1.20.1-580-server.jar:?]
        at net.minecraft.class_3324.method_14586(class_3324.java:1454) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_14384(class_3248.java:612) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.redirect$eah000$fabric-networking-api-v1$handlePlayerJoin(class_3248.java:1063) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_18784(class_3248.java:68) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:2111) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at java.lang.invoke.DirectMethodHandle.checkBase(DirectMethodHandle.java:547) ~[?:?]
        at jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.get(MethodHandleObjectFieldAccessorImpl.java:57) ~[?:?]
        at java.lang.reflect.Field.get(Field.java:428) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.nms.TinyReflection$1.get(TinyReflection.java:153) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.nms.TinyProtocol.getChannel(TinyProtocol.java:391) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.nms.TinyProtocol$4.onPlayerLogin(TinyProtocol.java:167) ~[?:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[%5B%E6%8F%92%E4%BB%B6%E6%94%AF%E6%8C%81%5Dbanner-1.20.1-580-server.jar:?]
        ... 15 more
[20:03:44] [Server thread/INFO]: Disconnecting com.mojang.authlib.GameProfile@5a816d3f[id=ec165265-8be4-38f6-a0ce-ddd6d6fe6322,name=Minecraft_KrC,properties={},legacy=false] (/120.244.194.11:35904): §7[§b§lL§3§lP§7]§r §cPermissions data for your user was not loaded during the pre-login stage - unable to continue. Please try again later. If you are a server admin, please check the console for any errors.
[20:03:44] [Server thread/INFO]: com.mojang.authlib.GameProfile@5a816d3f[id=ec165265-8be4-38f6-a0ce-ddd6d6fe6322,name=Minecraft_KrC,properties={},legacy=false] (/120.244.194.11:35904) lost connection: §7[§b§lL§3§lP§7]§r §cPermissions data for your user was not loaded during the pre-login stage - unable to continue. Please try again later. If you are a server admin, please check the console for any errors.
[20:03:44] [Server thread/WARN]: handleDisconnection() called twice

**Comment by windy664** [comment]
Deleting data is undoubtedly your best option.

**Comment by Auriny** [comment]
+1

**Comment by Nadir-Kotik** [comment]
The same problem occurs all the time. Can't fix it somehow.
