### ISSUE TITLE
隐形的盔甲架相关问题

### ISSUE THREAD

**Issue by CeydOuO** [MohistMC/Banner#258]
### I have confirmed that ...

- [X] Banner is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Fabric

### Banner version

591

### OS & Java versions

centos 9 jdk 17

### Plugins and Mods

```raw
没有模组。[00:15:03] [Server thread/INFO]: Plugins (24): LuckPerms, PlaceholderAPI, CMILib, NBTAPI, SkillAddon, Vault, LoneLibs, ProtocolLib, ItemsAdder, AuraSkills, AlonsoTags, TrChat, BanItem, HibiscusCommons, HMCCosmetics, GlobalMarketPlus, TAB-Bridge, WkKit, XConomy, CMI, CustomNameplates, InvSync, BungeeTabListPlus, PlugManX (PlugMan)
```

### Description

看看能不能修复net.minecraft.class_1297.nextEntityId()相关的代码，因为隐形的盔甲架大部分时间都看不见。。。

### Logs

 at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:2107) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'int net.minecraft.class_1297.nextEntityId()'
        at me.lojosho.hibiscuscommons.nms.v1_20_R1.NMSHandler.getNextEntityId(NMSHandler.java:34) ~[?:?]
        at me.lojosho.hibiscuscommons.util.ServerUtils.getNextEntityId(ServerUtils.java:15) ~[?:?]
        at com.hibiscusmc.hmccosmetics.user.manager.UserBackpackManager.<init>(UserBackpackManager.java:40) ~[?:?]
        at com.hibiscusmc.hmccosmetics.user.CosmeticUser.spawnBackpack(CosmeticUser.java:375) ~[?:?]
        at com.hibiscusmc.hmccosmetics.user.CosmeticUser.addPlayerCosmetic(CosmeticUser.java:118) ~[?:?]
        at com.hibiscusmc.hmccosmetics.user.CosmeticUser.addPlayerCosmetic(CosmeticUser.java:96) ~[?:?]
        at com.hibiscusmc.hmccosmetics.gui.type.types.TypeCosmetic.run(TypeCosmetic.java:110) ~[?:?]
        at com.hibiscusmc.hmccosmetics.gui.Menu.lambda$updateItem$6(Menu.java:249) ~[?:?]
        at com.hisbiscusmc.hmccosmetics.gui.guis.GuiListener.onGuiClick(GuiListener.java:102) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303) ~[banner-1.20.1-591-server.jar:?]

**Comment by Mgazul** [comment]
Fixed
