### ISSUE TITLE
[bug] rcon无法使用

### ISSUE THREAD

**Issue by shoucandanghehe** [MohistMC/Banner#260]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

1.20.1-660

### Java 版本 | 操作系统

Windows11 Zulu21.34+19-CA

### 相关 Mod/插件 的名称及版本

```raw
plugins
[10:32:24] [Server thread/INFO]: Plugins (0):
[10:32:24] [WindowsStreamPump/ERROR]: Uncaught exception in thread "WindowsStreamPump"
java.lang.NoSuchMethodError: 'int org.fusesource.jansi.internal.Kernel32.WaitForSingleObject(long, int)'
        at org.jline.terminal.impl.jansi.win.JansiWinSysTerminal.processConsoleInput(JansiWinSysTerminal.java:138) ~[org_jline_jline-terminal-jansi-3.21.0-6c6d8b747fdb6f1b.jar:?]
        at org.jline.terminal.impl.AbstractWindowsTerminal.pump(AbstractWindowsTerminal.java:460) ~[org_jline_jline-terminal-3.21.0-f6986d22c285dcdd.jar:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
fabricmods
[10:32:28] [Server thread/INFO]: Mods: adventure-platform-fabric, Banner Mod, mixin-tools, json-simple, dynamicenum, i18n, mysql-connector-j, commons-codec, commons-lang, Fabric API, Fabric Convention Tags, Fabric Loader, OpenJDK, javax.inject, jline, MixinExtras, mapping-io, adventure-api, adventure-key, adventure-platform-api, adventure-text-logger-slf4j, adventure-text-minimessage, adventure-text-serializer-ansi, adventure-text-serializer-gson, adventure-text-serializer-json, adventure-text-serializer-legacy, adventure-text-serializer-plain, examination-api, examination-string, bungeecord-chat, SpecialSource, terminalconsoleappender, log4j-iostreams, checker-qual, jansi, jline-reader, jline-terminal, jline-terminal-jansi, sqlite-jdbc, snakeyaml
```
```


### 错误描述

安装banner mod后，rcon任何命令都无法使用
```
❯ .\rcon.exe -a 127.0.0.1:25575 -p ***
Waiting commands for 127.0.0.1:25575 (or type :q to exit)
> help
Error executing: help (Cannot invoke "net.minecraft.class_3350.method_14702()" because "rconConsoleSource1" is null)
> help
Error executing: help (Cannot invoke "net.minecraft.class_3350.method_14702()" because "rconConsoleSource1" is null)
>
```

### 复现步骤

1. 安装banner
2. 使用rcon

### 报错信息

[latest.log](https://github.com/user-attachments/files/15860841/latest.log)


### 复现用压缩包下载链接(可选)

_No response_

**Comment by Wu-jiyan** [comment]
我有相同的问题
