### ISSUE TITLE
隐形的盔甲架不正常显示问题

### ISSUE THREAD

**Issue by CeydOuO** [MohistMC/Banner#263]
### I have confirmed that ...

- [X] Banner is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Fabric

### Banner version

600

### OS & Java versions

centos7 jdlk17

### Plugins and Mods

```raw
mods:banner
plugins: Citizens HMCCosmetics HibiscusCommons TAB
```

### Description

TAB的多行名字显示，是通过隐形盔甲架处理的 ，然后不显示。
cosmetics也是通过隐形盔甲架处理的，也不显示
citizens的多行名字通过holo处理的，服务器开启的时候插件第一次加载不显示npc的名字，需要reload才显示。
基本上就是隐形盔甲架的问题
报错出现了一个。

### Logs

Caused by: java.lang.IllegalAccessError: class me.lojosho.hibiscuscommons.nms.v1_20_R1.NMSHandler tried to access private method 'int net.minecraft.class_1297.nextEntityId()' (me.lojosho.hibiscuscommons.nms.v1_20_R1.NMSHandler is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @42bce73; net.minecraft.class_1297 is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @6f7fd0e6)
        at me.lojosho.hibiscuscommons.nms.v1_20_R1.NMSHandler.getNextEntityId(NMSHandler.java:34) ~[?:?]
        at me.lojosho.hibiscuscommons.util.ServerUtils.getNextEntityId(ServerUtils.java:15) ~[?:?]
        at com.hibiscusmc.hmccosmetics.user.manager.UserBackpackManager.<init>(UserBackpackManager.java:40) ~[?:?]
        at com.hibiscusmc.hmccosmetics.user.CosmeticUser.spawnBackpack(CosmeticUser.java:375) ~[?:?]
        at com.hibiscusmc.hmccosmetics.user.CosmeticUser.addPlayerCosmetic(CosmeticUser.java:118) ~[?:?]
        at com.hibiscusmc.hmccosmetics.user.CosmeticUser.addPlayerCosmetic(CosmeticUser.java:96) ~[?:?]
        at com.hibiscusmc.hmccosmetics.gui.type.types.TypeCosmetic.run(TypeCosmetic.java:110) ~[?:?]
        at com.hibiscusmc.hmccosmetics.gui.Menu.lambda$updateItem$6(Menu.java:249) ~[?:?]
        at com.hisbiscusmc.hmccosmetics.gui.guis.GuiListener.onGuiClick(GuiListener.java:102) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303) ~[banner-1.20.1-600-server.jar:?]
        ... 20 more

**Comment by Mgazul** [comment]
Fixed
