### ISSUE TITLE
banner can't use in 1.21 fabric

### ISSUE THREAD

**Issue by Ghostmole1** [MohistMC/Banner#267]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

banner-1.21-1.21

### Java 版本 | 操作系统

System : windows 11; Java: java version "22.0.1" 2024-04-16

### 相关 Mod/插件 的名称及版本

```raw
banner-1.21-1.21
fabric-api-0.100.3+1.21
```

### 错误描述

[15:55:34] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchMethodError: 'void sun.misc.Unsafe.ensureClassInitialized(java.lang.Class)'
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]
Caused by: java.lang.NoSuchMethodError: 'void sun.misc.Unsafe.ensureClassInitialized(java.lang.Class)'
        at com.mohistmc.dynamicenum.MohistDynamEnum.<clinit>(MohistDynamEnum.java:42) ~[com_mohistmc_dynamicenum-0.2-f16473361bc717d2.jar:?]
        at com.mohistmc.banner.bukkit.BukkitExtraConstants.<clinit>(BukkitExtraConstants.java:62) ~[banner-1.21-1.21.jar:?]
        at MC/net.minecraft.class_2473.<clinit>(class_2473.java:33) ~[server-intermediary.jar:?]
        at MC/net.minecraft.class_2246.<clinit>(class_2246.java:170) ~[server-intermediary.jar:?]
        at MC/net.minecraft.class_2358.method_10199(class_2358.java:336) ~[server-intermediary.jar:?]
        at MC/net.minecraft.class_2966.method_12851(class_2966.java:52) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:108) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
        ... 3 more

### 报错信息

[2024-06-24-1.log.gz](https://github.com/user-attachments/files/15951624/2024-06-24-1.log.gz)

**Comment by Mgazul** [comment]
use jdk21

**Comment by Ghostmole1** [comment]
> use jdk21

there is a new problem
[latest.log](https://github.com/user-attachments/files/15951814/latest.log)
