### ISSUE TITLE
[gradlew runServer] banner.mixins.json:world.level.block.MixinBambooStalkBlock

### ISSUE THREAD

**Issue by Merith-TK** [MohistMC/Banner#28]
Inside of gitpod I ran `./gradlew runServer` and this happened, I think Banner no like Bamboo

[debug.log](https://pastebin.com/zB3ZR8ic)

`latest.log`
```
[18:54:20] [main/INFO] (FabricLoader/GameProvider) Loading Minecraft 1.19.4 with Fabric Loader 0.14.17
[18:54:20] [main/INFO] (FabricLoader) Loading 38 mods:
	- banner 8
	- fabric-api 0.75.3+1.19.4
	- fabric-api-base 0.4.23+9ff28bced8
	- fabric-api-lookup-api-v1 1.6.24+49abcf7ed8
	- fabric-biome-api-v1 13.0.5+fe9afa9dd8
	- fabric-block-api-v1 1.0.5+e022e5d1d8
	- fabric-command-api-v2 2.2.4+ae0966bad8
	- fabric-content-registries-v0 3.5.6+ae0966bad8
	- fabric-convention-tags-v1 1.3.0+6baaf971d8
	- fabric-crash-report-info-v1 0.2.14+aeb40ebed8
	- fabric-data-generation-api-v1 11.3.4+5da15ca1d8
	- fabric-dimensions-v1 2.1.44+7f87f8fad8
	- fabric-entity-events-v1 1.5.12+e45f7c65d8
	- fabric-events-interaction-v0 0.4.42+a1ccd7bfd8
	- fabric-game-rule-api-v1 1.0.32+a1ccd7bfd8
	- fabric-gametest-api-v1 1.2.1+ae0966bad8
	- fabric-item-api-v1 2.1.15+ae0966bad8
	- fabric-item-group-api-v1 3.0.2+e45f7c65d8
	- fabric-lifecycle-events-v1 2.2.14+5da15ca1d8
	- fabric-loot-api-v2 1.1.24+75e98211d8
	- fabric-message-api-v1 5.1.0+1ee8be40d8
	- fabric-mining-level-api-v1 2.1.36+49abcf7ed8
	- fabric-networking-api-v1 1.2.21+4e68ac5bd8
	- fabric-object-builder-api-v1 7.0.0+63b515f4d8
	- fabric-particles-v1 1.0.22+f1e4495bd8
	- fabric-recipe-api-v1 1.0.5+a1ccd7bfd8
	- fabric-registry-sync-v0 2.1.1+a383ab97d8
	- fabric-rendering-data-attachment-v1 0.3.27+afca2f3ed8
	- fabric-rendering-fluids-v1 3.0.20+f1e4495bd8
	- fabric-resource-conditions-api-v1 2.3.0+e6c7d4eed8
	- fabric-resource-loader-v0 0.10.9+711cde8ad8
	- fabric-screen-handler-api-v1 1.3.17+5da15ca1d8
	- fabric-transfer-api-v1 3.0.1+9003cbe9d8
	- fabric-transitive-access-wideners-v1 3.0.2+63b515f4d8
	- fabricloader 0.14.17
	- java 17
	- minecraft 1.19.4
	- mm 2.1
[18:54:21] [main/INFO] (FabricLoader/Mixin) SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/gitpod/.gradle/caches/modules-2/files-2.1/net.fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/e13b4069fe3555969811d4474f78576c707bbe1c/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[18:54:21] [main/INFO] (FabricLoader/Mixin) Loaded Fabric development mappings for mixin remapper!
[18:54:21] [main/INFO] (FabricLoader/Mixin) Compatibility level set to JAVA_17
[18:54:22] [main/INFO] (Mohist Banner) Loading libraries, please wait...
[18:54:22] [main/INFO] (KnotHelper) Loading library snakeyaml-1.33.jar
[18:54:22] [main/INFO] (KnotHelper) Loading library maven-resolver-provider-3.8.5.jar
[18:54:22] [main/INFO] (KnotHelper) Loading library maven-resolver-connector-basic-1.7.3.jar
[18:54:22] [main/INFO] (KnotHelper) Loading library maven-resolver-transport-http-1.7.3.jar
[18:54:22] [main/INFO] (KnotHelper) Loading library jansi-1.18.jar
[18:54:22] [main/INFO] (KnotHelper) Loading library jline-2.14.6.jar
[18:54:22] [main/INFO] (KnotHelper) Loading library json-simple-1.1.1.jar
[18:54:22] [main/INFO] (KnotHelper) Loading library sqlite-jdbc-3.41.0.0.jar
[18:54:22] [main/INFO] (KnotHelper) Loading library mysql-connector-j-8.0.32.jar
[18:54:22] [main/INFO] (KnotHelper) Loading library SpecialSource-1.11.0.jar
[18:54:22] [main/INFO] (KnotHelper) Loading library bungeecord-chat-1.16-R0.4.jar
[18:54:22] [main/INFO] (KnotHelper) Loading library tools-1.3.0.jar
[18:54:22] [main/INFO] (KnotHelper) Loading library mohistremapper-0.3.jar
[18:54:22] [main/INFO] (KnotHelper) Loading library dynamicenum-0.1.jar
[18:54:22] [main/INFO] (KnotHelper) Loading library i18n-0.2.jar
[18:54:22] [main/INFO] (KnotHelper) Loading library log4j-iostreams-2.20.0.jar
[18:54:22] [main/INFO] (KnotHelper) Loading library commons-io-2.11.0.jar
[18:54:22] [main/INFO] (KnotHelper) Loading library commons-lang-2.6-mohist.jar
[18:54:27] [main/ERROR] (FabricLoader/Mixin) Mixin apply for mod banner failed banner.mixins.json:world.level.block.MixinBambooStalkBlock from mod banner -> net.minecraft.world.level.block.BambooStalkBlock: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException PROTECTED @Overwrite method growBamboo in banner.mixins.json:world.level.block.MixinBambooStalkBlock from mod banner cannot reduce visibiliy of PUBLIC target method
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: PROTECTED @Overwrite method growBamboo in banner.mixins.json:world.level.block.MixinBambooStalkBlock from mod banner cannot reduce visibiliy of PUBLIC target method
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.conformVisibility(MixinPreProcessorStandard.java:479) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:452) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachOverwriteMethod(MixinPreProcessorStandard.java:416) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:346) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:299) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) [fabric-loader-0.14.17.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
	at net.minecraft.world.level.block.FireBlock.bootStrap(FireBlock.java:326) [minecraft-merged-project-root-1.19.4-loom.mappings.1_19_4.layered+hash.528350982-v2.jar:?]
	at net.minecraft.server.Bootstrap.bootStrap(Bootstrap.java:46) [minecraft-merged-project-root-1.19.4-loom.mappings.1_19_4.layered+hash.528350982-v2.jar:?]
	at net.minecraft.server.Main.main(Main.java:109) [minecraft-merged-project-root-1.19.4-loom.mappings.1_19_4.layered+hash.528350982-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.17.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
[18:54:27] [main/ERROR] (Minecraft) Failed to start the minecraft server
java.lang.RuntimeException: Mixin transformation of net.minecraft.world.level.block.BambooStalkBlock failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.17.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.world.level.block.FireBlock.bootStrap(FireBlock.java:326) ~[minecraft-merged-project-root-1.19.4-loom.mappings.1_19_4.layered+hash.528350982-v2.jar:?]
	at net.minecraft.server.Bootstrap.bootStrap(Bootstrap.java:46) ~[minecraft-merged-project-root-1.19.4-loom.mappings.1_19_4.layered+hash.528350982-v2.jar:?]
	at net.minecraft.server.Main.main(Main.java:109) [minecraft-merged-project-root-1.19.4-loom.mappings.1_19_4.layered+hash.528350982-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.17.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.17.jar:?]
	... 11 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [banner.mixins.json:world.level.block.MixinBambooStalkBlock from mod banner] from phase [DEFAULT] in config [banner.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.17.jar:?]
	... 11 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: PROTECTED @Overwrite method growBamboo in banner.mixins.json:world.level.block.MixinBambooStalkBlock from mod banner cannot reduce visibiliy of PUBLIC target method
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.conformVisibility(MixinPreProcessorStandard.java:479) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:452) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachOverwriteMethod(MixinPreProcessorStandard.java:416) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:346) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:299) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.17.jar:?]
	... 11 more
```

**Comment by 1798643961** [comment]
It is still in WIP，waiting for mixin work

**Comment by Merith-TK** [comment]
Alright, I figured keeping an log of what is broken and what isnt is helpful either way
