### ISSUE TITLE
锂优化模组和地毯和其附属mod无法使用

### ISSUE THREAD

**Issue by MSCMDD** [MohistMC/Banner#287]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

1.20.1-688

### Java 版本 | 操作系统

openjdk version "21.0.3" 2024-04-16 LTS OpenJDK Runtime Environment (build 21.0.3+10-LTS) OpenJDK 64-Bit Server VM (build 21.0.3+10-LTS, mixed mode, sharing)

### 相关 Mod/插件 的名称及版本

```raw
[锂] lithium-fabric-mc1.20.1-0.11.2.jar
[地毯tis]carpet-tis-addition-mc1.20.1-v1.59.3.jar
[PCA]PluslsCarpetAddition-all-0.3.169+6510223-beta.jar
[地毯] fabric-carpet-1.20-1.4.112+v230608.jar
```

### 错误描述

生电地毯端地毯mod及其附属无法使用
还有锂优化mod也无法使用

### 复现步骤

1. 安装Banner，将
```
[锂] lithium-fabric-mc1.20.1-0.11.2.jar
[地毯tis]carpet-tis-addition-mc1.20.1-v1.59.3.jar
[PCA]PluslsCarpetAddition-all-0.3.169+6510223-beta.jar
[地毯] fabric-carpet-1.20-1.4.112+v230608.jar
```
放到mods文件夹
启动
返回报错

### 报错信息

[11:55:32] [main/WARN]: Error loading class: net/additionz/misc/FletchingScreenHandler (java.lang.ClassNotFoundException: net/additionz/misc/FletchingScreenHandler)
[11:55:33] [main/ERROR]: Failed to load language file assets/carpet/lang/pt_br.json from D:\MineServer\MCDR_CAT\CAT\mods\[地毯] fabric-carpet-1.20-1.4.112+v230608.jar.
[11:55:33] [main/ERROR]: Failed to fetch class node carpettisaddition.settings.CarpetRuleRegistrar:
[11:55:33] [main/INFO]: [MemoryLeakFix] Will be applying 1 memory leak fixes!
[11:55:33] [main/INFO]: [MemoryLeakFix] Currently enabled memory leak fixes: [biomeTemperatureLeak]
[11:55:33] [main/WARN]: Error loading class: net/additionz/misc/FletchingScreenHandler (java.lang.ClassNotFoundException: net/additionz/misc/FletchingScreenHandler)
[11:55:33] [main/WARN]: Error loading class: net/additionz/misc/FletchingScreenHandler (java.lang.ClassNotFoundException: net/additionz/misc/FletchingScreenHandler)
[11:55:34] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.0).
[11:55:39] [main/WARN]: @Redirect conflict. Skipping banner.mixins.json:server.level.MixinServerLevel from mod banner->@Redirect::banner$timeSkip(Lnet/minecraft/class_3218;J)V with priority 400, already redirected by pca.mixins.json:rule.sleepingDuringTheDay.MixinServerLevel from mod pca-1_20_1->@Redirect::onSetTimeOfDay(Lnet/minecraft/class_3218;J)V with priority 1000
[11:55:39] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3218 failed
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.0.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.16.0-launcher.1.0.1.jar:1.0.1]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.0.jar:?]
        ... 11 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector banner$timeSkip(Lnet/minecraft/class_3218;J)V in banner.mixins.json:server.level.MixinServerLevel from mod banner failed injection check, (0/1) succeeded. Scanned 0 target(s). Using refmap banner-refmap.json
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:531) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1490) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:752) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:330) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.0.jar:?]
        ... 11 more

**Comment by windy664** [comment]
just try to  use carpet?

**Comment by menxin123** [comment]
I had the same problem with the latest build, but I downgraded the version to banner-1.20.1-591-server.jar and it worked, the carpet was not available at the beginning of the range before and after the version of banner-1.20.1-570-server.jar, and my version of the game was 1.20.1
