### ISSUE TITLE
Critial issue for Brigadier injection commands

### ISSUE THREAD

**Issue by makrse** [MohistMC/Banner#344]
### I have confirmed that ...

- [ ] Banner is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Fabric

### Banner version

Banner 1.20.1 - 1.20.1-780, Java 65.0

### OS & Java versions

OS: UBUNTU, JAVA:openjdk version "21.0.5" 2024-10-15 LTS

### Plugins and Mods

```raw
CommandDefender-2.1.8
PL-Hide-1.5.22
CommandBlockerX-1.0.2
ProAntiTab-1.9.0
CommandWhitelist-Bukkit-2.10.0
```

### Description

All of above plugins to most common hide or deny commands to the regular users, tested that using each one alone without any other plugin alongise, just 1 of it , each one give the same error, deleting and recreating new world also do the same, but does not give any errors if the user joining it has Operator mode and does not has to do with any fabric mods, because all of it does not interact with inner commands modifications:

```


[10:28:25] [Server thread/ERROR] (Minecraft) Couldn't place player in world
java.lang.ClassCastException: class com.mojang.brigadier.tree.RootCommandNode cannot be cast to class com.mohistmc.banner.injection.commands.InjectionCommandNode (com.mojang.brigadier.tree.RootCommandNode and com.mohistmc.banner.injection.commands.InjectionCommandNode are in unnamed module of loader 'knot' @679b62af)
        at net.minecraft.class_2170.method_9241(class_2170.java:618) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_14596(class_3324.java:665) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_14576(class_3324.java:566) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_14570(class_3324.java:221) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_33800(class_3248.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_14384(class_3248.java:631) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.redirect$cio000$fabric-networking-api-v1$handlePlayerJoin(class_3248.java:1063) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_18784(class_3248.java:68) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:2102) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[10:28:25] [Server thread/INFO] (Minecraft) Steffa06 lost connection: Invalid player data
[10:28:25] [Server thread/WARN] (Minecraft) Failed to handle packet for /0000
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3222.method_5667()" because "serverPlayer" is null
        at net.minecraft.class_3324.method_14611(class_3324.java:1382) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_10839(class_3244.java:1228) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10768(class_2535.java:450) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:263) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:2102) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by makrse** [comment]
Also theres issue using `levelmobs` `RoseStacker` `WildStack` plugins
