### ISSUE TITLE
Cannot place any head (mob, player, custom) because data is invalid or null (don´t exist)

### ISSUE THREAD

**Issue by tarquitet** [MohistMC/Banner#85]
### Commit ID

MohistMC/Banner/commit/89fa80ddbf26f268d19946f70f2a0bafc642ff13

### Log with Error

[21:59:46] [Server thread/ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@673f0106, suppressing error java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.state.BlockState.getBlock()" because "data" is null         at org.bukkit.craftbukkit.v1_20_R1.block.data.CraftBlockData.fromData(CraftBlockData.java:562) ~[Banner%20Mod-LATEST-%5B1.20.%5D.jar:?]         at net.minecraft.world.item.StandingAndWallBlockItem.getPlacementState(StandingAndWallBlockItem.java:563) ~[server-intermediary.jar:?]         at net.minecraft.world.item.BlockItem.place(BlockItem.java:75) ~[server-intermediary.jar:?]         at net.minecraft.world.item.BlockItem.useOn(BlockItem.java:50) ~[server-intermediary.jar:?]         at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:1329) ~[server-intermediary.jar:?]         at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:1507) ~[server-intermediary.jar:?]         at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:940) ~[server-intermediary.jar:?]         at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1140) ~[server-intermediary.jar:?]         at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:34) ~[server-intermediary.jar:?]         at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:8) ~[server-intermediary.jar:?]         at net.minecraft.network.protocol.PacketUtils.mda21612$banner$lambda$ensureRunningOnSameThread$0$0(PacketUtils.java:529) ~[server-intermediary.jar:?]         at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-intermediary.jar:?]         at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:156) ~[server-intermediary.jar:?]         at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[server-intermediary.jar:?]         at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:782) ~[server-intermediary.jar:?]         at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:164) ~[server-intermediary.jar:?]         at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:130) ~[server-intermediary.jar:?]         at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:764) ~[server-intermediary.jar:?]         at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:758) ~[server-intermediary.jar:?]         at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:115) ~[server-intermediary.jar:?]         at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:742) ~[server-intermediary.jar:?]         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:2132) ~[server-intermediary.jar:?]         at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:265) ~[server-intermediary.jar:?]         at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Description of Error

The problem is explained in the title but, the problem happens to with vanilla heads.
Without banner mod works well.

Mods or plugins about player heads give the problem and vanilla commands too (don't give any errors with the commands, only when the head is placed).

Psd: Sorry 4 bad eng.

**Comment by wdog5** [comment]
try check the lastest version again

**Comment by tarquitet** [comment]
I did it and it didn't work either
