### ISSUE TITLE
安装dehydration-1.3.4模组不能启动服务端

### ISSUE THREAD

**Issue by 5ur3z** [MohistMC/Banner#97]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

banner-1.20.1-304.jar

### Java 版本 | 操作系统

系统：Windows 11  Java：zulu18.32.13-ca-jdk18.0.2.1-win_x64

### 相关 Mod/插件 的名称及版本

```raw
cloth-config-11.1.106-fabric.jar
dehydration-1.3.4.jar
fabric-api-0.86.1+1.20.1.jar
banner-1.20.1-304.jar
```

### 错误描述

Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69)
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_2358.method_10199(class_2358.java:326)
	at net.minecraft.class_2966.method_12851(class_2966.java:54)
	at net.minecraft.server.Main.main(Main.java:109)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3924 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at net.minecraft.class_2246.<clinit>(class_2246.java:939)
	... 8 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 13 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method litServerTickMixin(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;Lnet/minecraft/class_3924;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;ZILnet/minecraft/class_1799;Lnet/minecraft/class_1263;Lnet/minecraft/class_1799;)V in dehydration.mixins.json:CampfireBlockEntityMixin from mod dehydration failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap dehydration-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 16 more

### 复现步骤

安装dehydration-1.3.4.jar及clothconfig
启动服务端，无法启动
客户端正常启动

### 报错信息

[latest.log](https://github.com/MohistMC/Banner/files/12213674/latest.log)

**Comment by 5ur3z** [comment]
[mods.zip](https://github.com/MohistMC/Banner/files/12214056/mods.zip)

**Comment by DreamSoulFire** [comment]
理论上来说 不需要多安装一个cloth-config
因为高版本fabricapi没记错的话自带

**Comment by 5ur3z** [comment]
> 理论上来说 不需要多安装一个cloth-config 因为高版本fabricapi没记错的话自带

不安装的话会提示缺少cloth-config(

**Comment by DreamSoulFire** [comment]
悲(
