### ISSUE TITLE
NBTAPI后台警告

### ISSUE THREAD

**Issue by 5ur3z** [MohistMC/Banner#99]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

banner-1.20.1-304.jar

### Java 版本 | 操作系统

系统：Windows 11  Java：zulu18.32.13-ca-jdk18.0.2.1-win_x64

### 相关 Mod/插件 的名称及版本

```raw
item-nbt-api-plugin-2.11.3.jar
ShopGUIPlus-1.88.0.jar
Vault.jar
XConomy-Bukkit-2.22.1.jar
```

### 错误描述

NBTAPI后台警告

### 复现步骤

启动服务器，后台报错
游戏内执行/shopgui提示未启用插件

### 报错信息
[18:51:07] [Server thread/WARN]: [NBTAPI] Error during 'ItemConversionTest' test!
de.tr7zw.nbtapi.NbtApiException: [?]Rebuilt item did not match the original!
        at de.tr7zw.nbtapi.plugin.tests.items.ItemConversionTest.test(ItemConversionTest.java:27) ~[?:?]
        at de.tr7zw.nbtapi.plugin.NBTAPI.onEnable(NBTAPI.java:205) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[banner-1.20.1-304.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:348) ~[banner-1.20.1-304.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482) ~[banner-1.20.1-304.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:532) ~[banner-1.20.1-304.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:454) ~[banner-1.20.1-304.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zdh000$banner$enablePlugins(MinecraftServer.java:2244) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:339) ~[server-intermediary.jar:?]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:169) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:2084) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:51:07] [Server thread/INFO]: [NBTAPI] ItemConversionTest: [?]Rebuilt item did not match the original!
[18:51:07] [Server thread/WARN]: [NBTAPI] WARNING! This version of NBT-API seems to be broken with your Spigot version! Plugins that don't check properly may throw Exeptions, crash or have unexpected behaviors!

**Comment by 5ur3z** [comment]
[plugins.zip](https://github.com/MohistMC/Banner/files/12214048/plugins.zip)

**Comment by 5ur3z** [comment]
[shopGUI.zip](https://github.com/MohistMC/Banner/files/12214227/shopGUI.zip)
